### ISSUE TITLE
A Few Problems 

### ISSUE THREAD

**Issue by thematica** [ZhenjianYang/ZeroAoVoice-PSP#2]
hi,
i started playing Ao no Kiseki PSP version using PSV Adrenaline (without your voice patch)
then i found about your patch and applied it to my game

i have a few problem and i can't pinpoint the cause
1. i'm using PSV Adrenaline with Force high memory layout enabled, but the game didn't load. it won't show the load system data screen, instead it only show black screen. the same ISO works in PPSSPP. i already set Use PPSSPP = 0 but still won't load. (i'm using AT3 inside PAK format)

2. i have 2 save data, one is right before final boss in Prologue and the other one is the save data between chapter Prologue and chapter 1 (the one where the game asks you to save/continue). 
when i tried load the 1st one, it works okay. but the 2nd one crashes PPSSPP. i tried using other people's save data in chapter 1, it works okay too. is there any known bug for this "transition save"?

Thank You for this patch :)

**Comment by ZhenjianYang** [comment]
1. If you use the latest Adrenaline, Please refer to 2.2 and 2.3 in [README](https://github.com/ZhenjianYang/ZeroAoVoice-PSP#2how-to-let-it-work), didn't you forget to decrypt EBOOT.BIN or modify PARAM.SFO?

2. As I mentioned in 'readme.txt', not all savedatas saved in the original game will be compatible with the voice patched game. And for the  savedatas saved between two chapters, 100% not compatible. This is not a bug.

**Comment by thematica** [comment]
ahhh i'm so sorry, i misread your readme.txt 
i thought you're talking about savestates in emulator (it's quite normal to have strange effects if the ISO is modified)

about the EBOOT.BIN,
i'll check it tonight and post back since i'm using Sinh_Kresnik's guide
i'll try to decrypt it myself

Thank You

**Comment by ZhenjianYang** [comment]
I checked Sinh_Kresnik's guide. The EBOOT.BIN(renamed to BOOT.BIN in Sinh_Kresnik's Ao-Tools.rar) was not decrypted. This must be the problem.
You can decrypt EBOOT.BIN with PPSSPP (mentioned in 2.3 of [README](https://github.com/ZhenjianYang/ZeroAoVoice-PSP#2how-to-let-it-work))

And the bug mentioned in Sinh_Kresnik's guide, which may cause freezing when puck up shining spots, was fixed in the 20170714's [release](https://github.com/ZhenjianYang/ZeroAoVoice-PSP/releases). Please replace AddScnsToIso.exe and do step 6 once again.

**Comment by thematica** [comment]
ALRIGHT!!
it's working now, THANK YOU for your support

i'll close this "issue" right now 👍
